
INSERT INTO video_game_listings (name, company, platform, description, price, cover_photo_url, is_stocked, admin_id) VALUES

('Pokémon Legends: Arceus', 'Nintendo', 'Switch', 'Pokémon did not necessarily need to change. This game is sold extraordinarily well.', 5100, 'https://www.videogameschronicle.com/files/2021/08/pokemon-legends-arceus-1024x578.jpg', TRUE, 3);
('Rainbow 6 Extraction', 'Ubisoft', 'PlayStation 5', 'You remember what it is like to truly fear death in Extraction.', 1200, 'https://cdn.mos.cms.futurecdn.net/KrWRL9o3zDChkxvEFDLRh7-970-80.jpg.webp', FALSE, 10);
('OlliOlli World', 'Private Division', 'Switch', 'What makes OlliOlli World uniquely memorable is its slacker-utopia aesthetic. Who would not want to live on a planet that can be navigated only by kickflips?', 3000, 'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_1.0/c_scale,w_1100/ncom/en_US/games/switch/o/olliolli-world-switch/hero', TRUE, 1);
('Ghostwire: Tokyo', 'Bethesda Softworks', 'Windows PC', 'This is a game in which you will banish demons before stopping into an ersatz 7-Eleven for some health-restoring mochi.', 4900, 'https://i0.wp.com/bloody-disgusting.com/wp-content/uploads/2022/03/ghostwire-tokyo-review-header.jpg?w=1280&ssl=1', TRUE, 6);
('Lego Star Wars: The Skywalker Saga', 'Warner Bros', 'PlayStation 5', 'Yes! you will play through all of Attack of the Clones, and you will like it.', 4700, 'https://assets-prd.ignimgs.com/2022/04/04/lego-star-wars-skywalker-saga-1649085951953.jpg?width=1920', TRUE, 2);
('Dune: Spice Wars', 'Funcom', 'Windows PC', 'It is brutal, ornery, unfair, and quintessentially Dune.', 3000, 'https://cdn.vox-cdn.com/thumbor/hSykLBqiThcI3JraW4WFA0q8gQA=/0x0:1920x1080/920x613/filters:focal(807x387:1113x693):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/70716204/Early_Access_Launch_Date_Banner.0.png', FALSE, 11);
('Spider-Man Remastered', 'Insomniac Games', 'PlayStation 5', 'Play as an experienced Peter Parker, fighting big crime and iconic villains in Marvels New York', 5000, 'https://static.wikia.nocookie.net/spidermanps4/images/d/d4/Marvel%27s_Spider-Man_front_cover_%28US%29.png/revision/latest?cb=20201003182432', true, 1)
('Zelda', 'Nintendo', 'Switch', 'Breath of the Wild, a boundary-breaking new game in the acclaimed series.', 6700, 'https://assets-prd.ignimgs.com/2022/06/14/zelda-breath-of-the-wild-1655249167687.jpg?width=300&crop=1%3A1%2Csmart', true, 2)
('Castlevania', 'Konami', 'PS4', 'Lords of Shadow, the origin of Dracula and his legendary connection with the Belmonts was revealed.', 4500, 'https://static.wikia.nocookie.net/castlevania/images/e/e0/Castlevania_-_Netflix_-_02.jpg/revision/latest?cb=20170630190429', false, 3)
('Metal gear solid', 'Konama', 'PS4', ' The Soviet invasion of Afghanistan has brought a new edge to the Cold War', 2000, 'https://www.imdb.com/title/tt0180825/mediaviewer/rm2189671937/?ref_=tt_ov_i', true, 9)
('Chrono Trigger', 'Squaresoft', 'Super nintendo', 'Young Crono must travel through time to rescue his unfortunate companion from an intricate web of past and present perils', 3200, 'https://cdn.akamai.steamstatic.com/steam/apps/613830/header.jpg?t=1646911047', false, 12)
('Metroid', 'Nintendo', 'Wii', 'The Metroid™ Fusion game when she descends upon planet ZDR to investigate a mysterious transmission sent to the Galactic Federation', 8600, 'https://m.media-amazon.com/images/I/816ZIy1Y0-L._SY445_.jpg', false, 8)
('Monster Hunter', 'Capcom', 'Xbox', 'Monster Hunter Stories 2: Wings of Ruin offers both RPG and Monster Hunter fans a unique new experience with a rich storyline', 1900, 'https://cdn.akamai.steamstatic.com/steam/apps/582010/header.jpg?t=1661218531', true, 1)
('Resident Evil', 'Capcom', 'Gamecube', 'The next generation of survival horror rises in the form of Resident Evil Village, the eighth major entry in the Resident Evil series', 12000, 'https://assets.reedpopcdn.com/project-w-dbd.jpg/BROK/resize/690%3E/format/jpg/quality/75/project-w-dbd.jpg', true, 6)
('Super Mario World', 'Nintendo', 'Super nintendo', 'Pounce and climb through dozens of colorful stages! Mario (and his friends) can use power-ups like the Super Bell', 1000, 'https://user-images.githubusercontent.com/12776674/122607515-0e8d4600-d051-11eb-900b-1b072f5bbbad.png', true, 11)
('Mario Bros.3', 'Nintendo', 'Nintendo', ' A competitive clash comes to the Mushroom Kingdom! Super Mario Bros', 3400, 'https://static.wikia.nocookie.net/mario/images/7/71/Super_Mario_Bros._3_front_cover_%28US%29.png/revision/latest/scale-to-width-down/1200?cb=20190808190744', false, 3);
('Elden Ring', 'Bandai', 'PC', ' A New World Created By Hidetaka Miyazaki And George R. R. Martin. ELDEN RING, developed by FromSoftware, Inc', 6000, 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg?t=1654259241', TRUE, 3);
('God of War', 'playstation', 'PS4', 'His vengeance against the gods of Olympus far behind him, Kratos now lives as a man in the lands of Norse Gods and monsters', 54000, 'https://images-na.ssl-images-amazon.com/images/I/51qpkdw1+8L._SX377_BO1,204,203,200_.jpg', true, 1);
('Rogue Legacy', 'Cella Door', 'Xbox', 'Every child is unique. One child might be colorblind, another might have tourettes-- they could even be a dwarf', 61000, 'https://cdn.akamai.steamstatic.com/steam/apps/1253920/header.jpg?t=1661199818', TRUE, 6);
('Xenoblade Chronicles', 'Nintendo', 'Switch', 'Fighting to liveand living to fight - A brand new RPG adventure awaits in Xenoblade Chronicles 3', 58000, 'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_1.0/c_scale,w_700/ncom/en_US/games/switch/x/xenoblade-chronicles-definitive-edition-switch/hero', false, 2);
('Sentinels', 'Sega', 'Switch', 'Vanillaware signature artistic shine and gorgeous aesthetics will bring the characters and story of 13 Sentinels to life', 55000, 'https://images.squarespace-cdn.com/content/v1/5aa9b09612b13f9aecc1613a/1588118911531-OYHR79XP96H9TX17N5M7/SENTINELS+x+VALORANT?format=1000w', TRUE, 12);
